### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by wildhart** [albanian-xrm/Xrm-Entity-Serializer#7]
I'm using this library to serialize and then deserialize objects from CRM, but I always get the following exceptions:
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at XrmEntitySerializer.AttributeCollectionConverter.ReadCollection(JsonReader reader, Type objectType, AttributeCollection existingAttributes, JsonSerializer serializer, JArray jArray)
   at XrmEntitySerializer.CollectionTypeConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at CRMRefreshTool.Form1.LoadXML[T](String path) in C:\Projects\CRM Refresh Tool\CRM Refresh Tool\Form1.cs:line 367
...
```

My own code is exactly the same as the examples:
```
var org = context.pnl_organisationSet.ToList().FirstOrDefault();
SaveAsJSON(org, FILE_NAMES.XERO_ORGANISATIONS);
...
var restoredOrg = LoadJSON<pnl_organisation>(FILE_NAMES.XERO_ORGANISATIONS);
...

        private static void SaveAsJSON<T>(T data, string path)
        {
            var serializer = new EntitySerializer();
            using (var writer = new JsonTextWriter(new StreamWriter(path + ".json")))
            {
                serializer.Serialize(writer, data);
            }
        }

        private static T LoadJSON<T>(string path)
        {
            var serializer = new EntitySerializer();
            var data = default(T);
            using (JsonTextReader reader = new JsonTextReader(new StreamReader(path + ".json")))
            {
                data = serializer.Deserialize<T>(reader);
            }
            return data;
        }
```
I've looked through the .json file and can't see any duplicate attributes.

Any ideas why I'm getting this error?

**Comment by BetimBeja** [comment]
Hi @wildhart,
can you share a sample json that throws the exception? I am not able to replicate it for the moment.
if you want to share it in private send a email at `betim [dot] beja [at] xrm [dot] al`

thanks

**Comment by wildhart** [comment]
Hi @BetimBeja, thanks for offering to look into this.  Check your email...

**Comment by BetimBeja** [comment]
As I replied in the email this is a bug with Early-Bound entities that I will fix soon.
Thanks for reporting this!

**Comment by wildhart** [comment]
Tested and works for me!

Extremely impressive support, thank you very much!
